# Generated by Django 2.2.16 on 2022-04-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220422_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_relate', to='api.Recipe'),
            preserve_default=False,
        ),
    ]
