# Generated by Django 2.2.19 on 2022-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0003_auto_20220330_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Завтрак', (('color', '#E26C2D'), ('slug', 'breakfast'), ('name', 'завтрак'), ('id', '1'))), ('Обед', (('color', '#1111D'), ('slug', 'lunch'), ('name', 'обед'), ('id', '2'))), ('Завтрак', (('color', '#22222D'), ('slug', 'dinner'), ('name', 'ужин'), ('id', '3')))], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
