# Generated by Django 2.2.19 on 2022-03-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0004_auto_20220331_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
    ]
