# Generated by Django 2.2.19 on 2022-03-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0007_auto_20220331_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='_slug', to='recept.Tag'),
        ),
    ]
