# Generated by Django 2.2.19 on 2022-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0009_auto_20220331_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasgs',
            field=models.ManyToManyField(related_name='recipes_relate', to='recept.Tag'),
        ),
    ]
