# Generated by Django 2.2.19 on 2022-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0010_auto_20220331_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tasgs',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recept.Tag'),
        ),
    ]
