# Generated by Django 2.2.19 on 2022-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0011_auto_20220401_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
