# Generated by Django 2.2.19 on 2022-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0014_tagsinrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsinrecipe',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagsinrecipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
