# Generated by Django 2.2.19 on 2022-04-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0015_auto_20220402_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='m2m_tags', to='recept.Tag'),
        ),
    ]
