# Generated by Django 2.2.19 on 2022-04-07 12:11

from django.db import migrations, models
import recept.models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0016_auto_20220402_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[recept.models.Recipe.validate_null]),
        ),
    ]
