# Generated by Django 2.2.19 on 2022-04-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0018_auto_20220407_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridient',
            options={'ordering': ('id',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
    ]
