# Generated by Django 2.2.19 on 2022-04-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0019_auto_20220407_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_card',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='shop_card',
            name='unique_field',
        ),
    ]
