# Generated by Django 2.2.19 on 2022-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0020_auto_20220407_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_card',
            options={'verbose_name': 'корзина покупателя', 'verbose_name_plural': 'корзины покупателей'},
        ),
        migrations.AddConstraint(
            model_name='shop_card',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_field'),
        ),
    ]
